### ISSUE TITLE
Query Existing Google Sheet

### ISSUE THREAD

**Issue by MinuraPunchihewa** [google/google-visualization-python#45]
Hi guys,

I just wanted to know if it is possible to query an existing Google Sheet using this package? I have seen that this is possible with JavaScript as shown below,
```
var query = new google.visualization.Query(DATA_SOURCE_URL);
query.setQuery('select dept, sum(salary) group by dept');
query.send(handleQueryResponse);
```
https://developers.google.com/chart/interactive/docs/querylanguage#top_of_page

Is it possible to do something similar either through this package or something else?

**Comment by mishas** [comment]
This package is only for using of Google-visualization-API via Python. It has no capabilities or querying any data.

**Comment by MinuraPunchihewa** [comment]
Ah, apologies. If you look at the link given above though, it looks like the Google-Visualization API also has an endpoint for querying data. That is why I was wondering if this was supported.
